### ISSUE TITLE
Dir.Filename only checks cur

### ISSUE THREAD

**Issue by terinjokes** [luksen/maildir#12]
The implementation of Dir.Filename only checks the "cur" directory, so messages still in "new" can't be found.

https://github.com/luksen/maildir/blob/1f393bda6a0ffebb8f4a0d5bcbb5f2ed66a01c3c/maildir.go#L139

/cc @emersion since your fork also has this issue

**Comment by emersion** [comment]
This is by design, at least in my fork. Messages in new are unknown to the application before `Unseen` is called (it moves messages to cur).

**Comment by terinjokes** [comment]
I'm writing a program that generates a maildir from third-party sources that are somewhat expensive to query. I was using `Filename` to determine if something has already been fetched. If the user's MUA isn't running, nothing moves from new to cur, which means I'm blind things already fetched.

**Comment by luksen** [comment]
As @emersion said, this is by design. I like that the lib enforces that messages move to cur once they have been seen by software. It might make sense to do the moving yourself with `Unseen()` and rely on the metadata flags for whether the user has seen the messages.

Another option would be to keep track of the sync state on your own. I think for sync type software this makes the most sense, as reading two directories (with files potentially moving between them due to another mail software) is prone to race conditions.

**Comment by terinjokes** [comment]
While I disagree: I'm the delivery agent, not the user, and therefore I should never move things to cur (and thus take away the user's new mail notification), I can respect you wishing to scope the library to a specific set of use cases.

Should it be documented that `Filename` only returns things from cur? That delivery agents should only ever call `NewDelivery`?

> Another option would be to keep track of the sync state on your own.

This is what I ended up doing, in part due to this limitation. As I said in the above comment, the current documentation makes the behavior seem like a bug.

**Comment by luksen** [comment]
That's a good point. I pushed a change that should make it more clear, that keys only ever point to messages in cur.

**Comment by terinjokes** [comment]
Thanks! And thanks again for the library.
